# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: mynamespace
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: bXl1c2Vy # Base64 encoded value of 'myuser'
  SPRING_DATASOURCE_PASSWORD: bXlwYXNzd29yZA== # Base64 encoded value of 'mypassword'
