apiVersion: v1
kind: Service
metadata:
  name: my-spring-boot-app-service
  namespace: mynamespace
spec:
  selector:
    app: my-spring-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
