name: Continuous Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-boot-app:latest

      # Deploy to Kubernetes ---> option 1
      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@master
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply
          args: -f kubernetes/deployment.yaml -f kubernetes/service.yaml

      # Restart your Docker container with the latest image ---> option 2
      # TODO change the container name !!!
      - name: Restart Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_SSH_PORT }}
          script: |
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-boot-app:latest
            docker run -d --name your-container-name -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-boot-app:latest
